### ISSUE TITLE
When not logged in, clicking on an event name leads to an error

### ISSUE THREAD

**Issue by panpear** [10000-Lakes-Gaming/registration#147]
**Environment:** Test

### To reproduce:

1. Go to test-pfs-registration.herokuapp.com 
2. Click the 'test con' button under the 'Name' header
3. Error screen

This also happens when logged in on the same page when not signed up for the event.

**Recommendation:** Do not allow the event to be linked when not logged in.

**Unrelated recommendation:** Rename the 'Name' column to 'Event'.

**Comment by panpear** [comment]
Related Issue: On the registration page, the "Back to <con>" link also gives the same issue.

**Comment by Silbeg** [comment]
This actually has more to do with not being registered. 
If you aren't logged in, we cannot see user registrations.

**Comment by panpear** [comment]
Fixed via #165
