### ISSUE TITLE
For easier navigation as a user, I would like a 'back' or 'home' button after clicking on a receipt

### ISSUE THREAD

**Issue by panpear** [10000-Lakes-Gaming/registration#148]
The receipts' page does have a back to event button. But it would be convenient to have a 'back to last page' or 'home' button for easier navigation through the application.

To reproduce, you will need a receipt from a past event.
1. Click on the receipt.
2. Observe only a 'back to event' button on the receipt page.

**Comment by Silbeg** [comment]
@panpear I have added breadcrumbs to the top of the page, which should help some. I am going to leave this in the backlog  for now.
